services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  producer:
    build: ./producer
    depends_on:
      - kafka
    restart: always

  trainer:
    build: ./trainer
    command: ["python", "train.py"]
    depends_on:
      - redis

  stream_processor:
    build: ./stream_processor
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      REDIS_HOST: redis
    depends_on:
      - kafka
      - trainer

  model_server:
    build: ./model_server
    ports:
      - "8000:8000"
    depends_on:
      - stream_processor
      - redis

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - model_server
      - redis
